from matplotlib.pyplot import get
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_channel_transcript_api import YoutubeChannelTranscripts




def get_YT_sub(id):
    transcript_list = YouTubeTranscriptApi.list_transcripts(id)
    transcript = transcript_list.find_transcript(['de', 'en'])
    return transcript

#sub_de = get_YT_sub_de(id)
#sub_en = get_YT_sub_en(id)

if __name__ == "__main__":  
    url="TGHwdp1u_sk&t=515s"
    url= "https://www.youtube.com/watch?v=TGHwdp1u_sk&t=515s"
    id = url.replace("https://www.youtube.com/watch?v=", "")
    print(id)
    sub= get_YT_sub(id)
    print(sub.fetch())
    print(
    #transcript.video_id,

    #transcript.language,
    sub.language_code,
    # whether it has been manually created or generated by YouTube
    sub.is_generated,
    #whether this transcript can be translated or not
    sub.is_translatable,
    # a list of languages the transcript can be translated to
    # transcript.translation_languages,
    )   

